WM/WM/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WM.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        
    }
}

WM/WM/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WM_API.API;
using WM_API;
using WM_API.Models;

namespace WM.Controllers
{
    public class ProductsController : Controller
    {
        #region Products_Db
        public ActionResult ProductsDb()
        {
            List<Product> _allProducts = ProductsService.GetProductsFromDb();
            return View("ProductsDb", _allProducts);
        }

        public PartialViewResult ProductDetails()
        {
            return PartialView("_AddProduct");
        }

        [HttpPost]
        public ActionResult Create(ProductModel model)
        {
            ProductsService.Insert(model);
            return RedirectToAction("ProductsDb");
        }

        public PartialViewResult Delete(int id)
        {
            var productToDelete = ProductsService.GetProductById(id);
            return PartialView("_DeleteProduct", productToDelete);
        }

        [HttpPost]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                ProductsService.DeleteProductById(id);
                return RedirectToAction("Index","Home");
            }   
            catch
            {
                return View();
            }
        }

        public PartialViewResult Update(int id)
        {
            var result = ProductsService.GetProductById(id);
            return PartialView("_UpdateProduct", result);
        }


        [HttpPost]
        public ActionResult Edit(int id, ProductModel model)
        {
            ProductsService.Update(model);
            return RedirectToAction("ProductsDb");
        }
        #endregion


        
    }
}

WM/WM/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WM/WM/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WM/WM/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

WM/WM/Views/Products/ProductsDb.cshtml
@model List<WM_API.Product>

<button class="btn btn-primary" type="button" data-toggle="modal" data-target="#newProductModal">Add New Product</button>
<!--Add New Product modal-->
<div class="modal inmodal" id="newProductModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content animated fadeIn">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <i class="fa fa-building modal-icon"></i>
                <h4 class="modal-title">Add New Product</h4>
            </div>
            <div id="modalContentToLoad"></div>
        </div>
    </div>
</div>
<!------------------------->
<!--Update Product modal-->
<div class="modal inmodal" id="updateProductModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content animated fadeIn">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <i class="fa fa-building modal-icon"></i>
                <h4 class="modal-title">Update Product</h4>
            </div>
            <div id="modalContentToLoadUpdate"></div>
        </div>
    </div>
</div>
<!------------------------->
<!--Delete Product modal-->
<div class="modal inmodal" id="deleteProductModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content animated fadeIn">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <i class="fa fa-trash modal-icon"></i>
                <h4 class="modal-title">Are you sure you want to delete selected product?</h4>
            </div>
            <div id="modalContentToLoadDelete"></div>
        </div>
    </div>
</div>
<!------------------------->
<!--Product Details modal-->
<div class="modal inmodal" id="productDetailsModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content animated fadeIn">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <i class="fa fa-building modal-icon"></i>
                <h4 class="modal-title">Product Details</h4>
            </div>
            <div id="modalContentToLoadDetails"></div>
        </div>
    </div>
</div>
<!------------------------->

<table class="table">
    <thead>
        <tr>
            <th></th>
            <th>Name</th>
            <th>Description</th>
            <th>Category</th>
            <th>Manufacturer</th>
            <th>Supplier</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr class="gradeA">
                <td>
                    <button class="btn btn-primary btn-circle" type="button" data-toggle="modal" rel="@item.Id" data-target="#updateProductModal">Edit</button>
                    <button style=" background-color:red; border-color:red" class="btn btn-primary btn-circle" type="button" data-toggle="modal" data-target="#deleteProductModal" rel="@item.Id">Delete</button>
                </td>
                <td>@item.Name</td>
                <td>@item.Description</td>
                <td class="center">@item.Category</td>
                <td class="center">@item.Manufacturer</td>
                <td class="center">@item.Supplier</td>
                <td class="center">@item.Price</td>
            </tr>
        }
    </tbody>
</table>

@section Scripts{
    <script>
        //Add New
        $('#newProductModal').on('shown.bs.modal', function (e) {
            var url = '@Url.Action("ProductDetails", "Products")';
            $.get(url, function (response) {
                $('#modalContentToLoad').html(response);
            });
        });

        $("#newProductModal").on("submit", "#form-addNew", function (e) {
            e.preventDefault();  // prevent standard form submission

            var form = $(this);
            $.ajax({
                url: form.attr("action"),
                method: form.attr("method"),
                data: form.serialize(),
                success: function () {
                    $('#newProductModal').modal('hide');
                },
                error: function (response) {
                    alert("Product with that name already exists !")
                }
            })
            $("#newProductModal").on('hidden.bs.modal', function () {
                window.location.reload(true)
            });
        });

    //Update
        $("#updateProductModal").on('shown.bs.modal', function (e) {
            var $target = $(e.relatedTarget);
            var productId = $target.attr('rel');
            var url = '@Url.Action("Update", "Products")' + '/' + productId;
            $.get(url, function (response) {
                $('#modalContentToLoadUpdate').html(response);
            });
         });

        $("#updateProductModal").on("submit", "#form-updateProduct", function (e) {
            e.preventDefault();  // prevent standard form submission

            var form = $(this);
            $.ajax({
                url: form.attr("action"),
                method: form.attr("method"),  // post
                data: form.serialize(),
                success: function () {
                    $('#updateProductModal').modal('hide');
                },
                error: function (response) {
                    alert("Product with that name already exists !")
                }
            })
            $("#updateProductModal").on('hidden.bs.modal', function () {
                window.location.reload(true)
            });
        });

        //Delete
        $("#deleteProductModal").on('shown.bs.modal', function (e) {
            var $target = $(e.relatedTarget);
            var productId = $target.attr('rel');
            var url = '@Url.Action("Delete", "Products")' + '/' + productId;
            $.get(url, function (response) {
                $('#modalContentToLoadDelete').html(response);
            });
         });
    </script>
}

WM/WM/Views/Products/_AddProduct.cshtml
@model  WM_API.Product

@using (Html.BeginForm("Create", "Products", FormMethod.Post, new { id = "form-addNew" }))
{
    @Html.ValidationSummary(true)

    <div class="modal-body">
        <div class="form-group">
            <div class="label" style="color:black">Name:</div>
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger required" })
        </div>

        <div class="form-group">
            <div class="label" style="color:black">Description:</div>
            @Html.TextBoxFor(m => m.Description, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger required" })
        </div>

        <div class="form-group">
            <div class="label" style="color:black">Category:</div>
            @Html.TextBoxFor(m => m.Category, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Category, "", new { @class = "text-danger required" })
        </div>

        <div class="form-group">
            <div class="label" style="color:black">Manufacturer:</div>
            @Html.TextBoxFor(m => m.Manufacturer, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Manufacturer, "", new { @class = "text-danger required" })
        </div>

        <div class="form-group">
            <div class="label" style="color:black">Supplier:</div>
            @Html.TextBoxFor(m => m.Supplier, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Supplier, "", new { @class = "text-danger required" })
        </div>
        
        <div class="form-group">
            <div class="label" style="color:black">Price:</div>
            @Html.TextBoxFor(m => m.Price, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Price, "", new { @class = "text-danger required" })
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-white" data-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-primary">Save Changes</button>
        </div>
    </div>
}

WM/WM/Views/Products/_DeleteProduct.cshtml
@model  WM_API.Product

@using (Html.BeginForm("DeleteConfirmed", "Products", FormMethod.Post, new { id = "form-deleteProduct" }))
{
    @Html.ValidationSummary(true)
    @Html.HiddenFor(m => m.Id)

    <div class="modal-body">
        <div class="form-group">
            <div>Product Name:</div>
            <b>@Html.DisplayFor(m => m.Name, new { @class = "form-control" })</b>
        </div>

        <div class="modal-footer">
            <button type="submit" class="btn btn-danger">Yes</button>
            <button type="button" class="btn btn-white" data-dismiss="modal">No</button>
        </div>
    </div>
}

WM/WM/Views/Products/_UpdateProduct.cshtml
@model  WM_API.Product

@using (Html.BeginForm("Edit", "Products", FormMethod.Post, new { id = "form-updateProduct" }))
{
    @Html.ValidationSummary(true)
    @Html.HiddenFor(m => m.Id)

<div class="modal-body">
    <div class="form-group">
        <div class="label" style="color:black">Name:</div>
        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger required" })
    </div>

    <div class="form-group" style="color:black">
        <div class="label">Description:</div>
        @Html.TextBoxFor(m => m.Description, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger required" })
    </div>

    <div class="form-group" style="color:black">
        <div class="label">Category:</div>
        @Html.TextBoxFor(m => m.Category, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Category, "", new { @class = "text-danger required" })
    </div>

    <div class="form-group" style="color:black">
        <div class="label">Manufacturer:</div>
        @Html.TextBoxFor(m => m.Manufacturer, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Manufacturer, "", new { @class = "text-danger required" })
    </div>

    <div class="form-group">
        <div class="label">Supplier:</div>
        @Html.TextBoxFor(m => m.Manufacturer, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Manufacturer, "", new { @class = "text-danger required" })
    </div>

    <div class="form-group" style="color:black">
        <div class="label">Price:</div>
        @Html.TextBoxFor(m => m.Price, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Price, "", new { @class = "text-danger required" })
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-white" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-primary">Save Changes</button>
    </div>
</div>
}

WM/WM/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("ProductsDb", "ProductsDb", "Products")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>